<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH4NdnNZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH4NdnNZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH4NdnNZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH4NdnNZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH4NdnNZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'H4NdnNZ',
    'container.build_id' => '5b5950e7',
    'container.build_time' => 1713348600,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH4NdnNZ');
