controllers:
    resource: ../src/Controller/
    type: attribute

generate_pdf:
  path: /generate-pdf
  controller: App\Controller\PdfController::generatePdf
  methods: POST

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

homepage:
  path: /
  controller: App\Controller\HomeController::index

subscription_change:
  path: /subscription/change
  controller: App\Controller\SubscriptionController::changeSubscription

history:
  path: /history
  controller: App\Controller\HistoryController::index
